version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Creating venv"
      - python3 -m venv venv
      - echo "Activating venv"
      - source venv/bin/activate
      - echo "Installing ffmpeg"
      - wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
      # - curl -O [FFMPEG_DOWNLOAD_LINK] # Replace with the actual download link
      # - tar xzf [FFMPEG_TAR_FILE]      # Replace with the actual tar file name if it's a tar.gz file
      # - sudo mv ffmpeg /usr/local/bin/
      - echo "Installing dependencies"
      - pip install -r requirements.txt
      - echo "Creating env variables"
      - echo "OPEN_AI_KEY=$OPEN_AI_KEY" > .env
      - echo "Running Fred..."
      - venv/bin/python fred.py

  pre_build:
    commands:
      - echo "Pre-build steps..."

  build:
    commands:
      - echo "Building the project..."
      # Add any build commands specific to your project here.

  post_build:
    commands:
      - echo "Post-build steps..."

artifacts:
  files:
    - '**/*'
  discard-paths: yes
