version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Creating venv"
      - python3 -m venv venv
      - echo "Activating venv"
      - source venv/bin/activate
      - echo "Installing ffmpeg"
      - wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
      - tar -xf ffmpeg-release-amd64-static.tar.xz
      - ls # Check the extracted directory name
      - "EXTRACTED_DIR=$(find . -maxdepth 1 -type d | grep 'ffmpeg-') && echo 'Extracted FFmpeg directory:' $EXTRACTED_DIR"
      - mkdir -p /codebuild/output/src2440170049/src/ffmpeg
      - mv $EXTRACTED_DIR/ffmpeg /codebuild/output/src2440170049/src/ffmpeg/
      - chmod +x /codebuild/output/src2440170049/src/ffmpeg/ffmpeg
      - echo "Installing dependencies"
      - pip install -r requirements.txt
      - ffmpeg

  pre_build:
    commands:
      - echo "Pre-build steps..."

  build:
    commands:
      - echo "Building the project..."
      # Add any build commands specific to your project here.

  post_build:
    commands:
      - echo "Post-build steps..."

artifacts:
  files:
    - '**/*'
  discard-paths: yes
